services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      SQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${SQL_USER}" ]
    ports:
      - "${SQL_PORT:-5432}:5432"