"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

# Initialize environment variables
env = environ.Env(SECRET_KEY=(str, "(╯▔皿▔)╯"), DEBUG=(bool, False))

SECRET_KEY = env.str("SECRET_KEY")

BASE_DIR = Path(__file__).resolve().parent.parent

# Attempt to read .env file, but do not fail if it does not exist

ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    environ.Env.read_env(ENV_FILE.as_posix())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")
DOMAIN = env.str("DOMAIN", default="https://topasig.md")

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    # Theme
    "jazzmin",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_celery_results",
    "django_minio_backend",
    "drf_api_logger",
    # Internal apps
    "apps.ensurance",
    "apps.common",
    "apps.payment",
    "web",
    # Minio Cleanup
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware",
]

# CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
CSRF_COOKIE_DOMAIN = env.str("CSRF_COOKIE_DOMAIN", default=None)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Cors
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "token",
    "cache-control",
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env.str("SQL_ENGINE", "django.db.backends.postgresql"),
        "NAME": env.str("SQL_NAME"),
        "USER": env.str("SQL_USER"),
        "PASSWORD": env.str("SQL_PASSWORD"),
        "HOST": env.str("SQL_HOST"),
        "PORT": env.int("SQL_PORT", 5432),
        "CONN_MAX_AGE": env.int("SQL_CONN_MAX_AGE", 600),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Rest framework settings
REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
    "PAGE_SIZE": 50,
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.BaseFilterBackend",
        "rest_framework.filters.SearchFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
}


# Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Top Asig API",
    "DESCRIPTION": "Api for website topasig.md",
    "VERSION": "0.0.1",
    "SERVE_INCLUDE_SCHEMA": True,
}

# RCA Settings
RCA_USERNAME = env.str("RCA_USERNAME")
RCA_PASSWORD = env.str("RCA_PASSWORD")
RCA_URL = env.str("RCA_URL", default="https://rcaapi-test.bnm.md/RcaExportService.asmx?WSDL")

# Locales
DEFAULT_LANG = "en"
LANGUAGES = [
    (DEFAULT_LANG, _("English")),
    ("ro", _("Romanian")),
    ("ru", _("Russian")),
]

LOCALE_PATHS = (BASE_DIR / "locale",)

# Asig settings
ASIG_IDNP = env.str("ASIG_IDNP")
ASIG_IBAN = env.str("ASIG_IBAN")

# Victoria settings
VICTORIA_BASE_URL = env.str("VICTORIA_BASE_URL")
MIA_BASE_URL = env.str("MIA_BASE_URL")
MIA_USERNAME = env.str("MIA_USERNAME")
MIA_PASSWORD = env.str("MIA_PASSWORD")

# Celery settings
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL")
CELERY_CACHE_BACKEND = "default"
CELERY_TIMEZONE = "Europe/Chisinau"

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 5 * 60  # 5 minutes
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 7 * 24 * 60 * 60  # 1 week

CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_ACKS_LATE = True

CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_PRIORITY_DEFAULT = 1
CELERY_RESULT_BACKEND = "django-db"

CELERY_BEAT_SCHEDULE = {
    "update_qr_status": {
        "task": "apps.payment.tasks.update_qr_status",
        "schedule": 10,  # every 10 seconds
    },
}

# Minio
MINIO_ENDPOINT = env.str("MINIO_ENDPOINT")
MINIO_EXTERNAL_ENDPOINT = env.str("MINIO_EXTERNAL_ENDPOINT", default=MINIO_ENDPOINT)
MINIO_ACCESS_KEY = env.str("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = env.str("MINIO_SECRET_KEY")
MINIO_USE_HTTPS = env.bool("MINIO_STORAGE_USE_HTTPS", default=False)
MINIO_EXTERNAL_ENDPOINT_USE_HTTPS = env.bool("MINIO_EXTERNAL_ENDPOINT_USE_HTTPS", default=MINIO_USE_HTTPS)
MINIO_MEDIA_FILES_BUCKET = "media"
MINIO_STATIC_FILES_BUCKET = "static"
STORAGES = {
    "default": {
        "BACKEND": "django_minio_backend.models.MinioBackend",
    },
    "staticfiles": {
        "BACKEND": "django_minio_backend.models.MinioBackendStatic",
    },
}
MINIO_PUBLIC_BUCKETS = [
    MINIO_MEDIA_FILES_BUCKET,
    MINIO_STATIC_FILES_BUCKET,
]

# SMTP settings
EMAIL_BACKEND = env.str("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env.str("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

# Logging
DRF_API_LOGGER_DATABASE = True
DRF_API_LOGGER_SKIP_URL_NAME = ["health-check", "schema-swagger-ui", "schema-redoc", "schema-swagger"]
DRF_API_LOGGER_SKIP_NAMESPACE = ["admin"]
DRF_API_LOGGER_SLOW_API_ABOVE = 2000

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "Top Asig",
    "site_header": "Top Asig",
    "welcome_sign": "Welcome to Top Asig",
    "navigation_expanded": True,
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "ensurance.File": "fas fa-file",
        "ensurance.RCACompany": "fas fa-building",
        "payment.QrCode": "fas fa-money-check",
        "drf_api_logger.APILogsModel": "fas fa-clipboard-list",
        "django_celery_results.TaskResult": "fas fa-tasks",
        "django_celery_results.GroupResult": "fas fa-tasks",
    },
}
