# Generated by Django 5.1.4 on 2025-01-09 20:00

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='media'), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
