# Generated by Django 5.1.4 on 2025-01-13 20:49

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='media'), upload_to=django_minio_backend.models.iso_date_prefix)),
                ('type', models.CharField(choices=[('RCA', 'RCA'), ('GreenCard', 'Green Card'), ('MedicalInsurance', 'Medical Insurance'), ('QR', 'QR'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
