# Generated by Django 5.1.4 on 2025-01-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0003_file_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
