# Generated by Django 5.1.4 on 2025-01-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0005_rcacompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='rcacompany',
            options={'verbose_name': 'RCA Company', 'verbose_name_plural': 'RCA Companies'},
        ),
    ]
