# Generated by Django 5.1.4 on 2025-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0006_alter_file_options_alter_rcacompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcacompany',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
    ]
