# Generated by Django 5.1.4 on 2025-03-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0008_medicalinsurancecompany'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('external_id', 'type')},
        ),
    ]
