# Generated by Django 5.1.4 on 2025-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0009_alter_file_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
