# Generated by Django 5.1.4 on 2025-01-04 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of the QR Code', unique=True)),
                ('qr_type', models.CharField(choices=[('DYNM', 'Dynamic'), ('STAT', 'Static'), ('HYBR', 'Hybrid')], default='DYNM', help_text='Type of the QR Code', max_length=4)),
                ('amount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Controlled', 'Controlled'), ('Free', 'Free')], default='Fixed', help_text='Type of the amount associated with the QR Code', max_length=10)),
                ('pmt_context', models.CharField(blank=True, choices=[('m', 'Mobile Payment'), ('e', 'E-commerce Payment'), ('i', 'Invoice Payment'), ('0', 'Other')], help_text='Payment context', max_length=1, null=True)),
                ('qr_as_text', models.TextField(blank=True, help_text='QR code represented as text', null=True)),
                ('qr_as_image', models.ImageField(blank=True, help_text='QR code image', null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Replaced', 'Replaced'), ('Inactive', 'Inactive')], default='Active', help_text='Current status of the QR Code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
