# Generated by Django 5.1.4 on 2025-01-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_as_image',
            field=models.TextField(blank=True, help_text='QR code represented as an image', null=True),
        ),
    ]
