# Generated by Django 5.1.4 on 2025-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_qrcode_qr_as_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Replaced', 'Replaced'), ('Inactive', 'Inactive')], db_index=True, default='Active', help_text='Current status of the QR Code', max_length=10),
        ),
    ]
