# Generated by Django 5.1.4 on 2025-01-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_qrcode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the QR code has been used'),
        ),
    ]
