# Generated by Django 5.1.4 on 2025-01-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_qrcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the QR code has been used'),
        ),
    ]
