# Generated by Django 5.1.4 on 2025-01-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_qrcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_as_image',
            field=models.TextField(blank=True, help_text='QR code represented as an image encoded in base64', null=True),
        ),
    ]
