# Generated by Django 5.1.4 on 2025-01-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0004_file_name'),
        ('payment', '0006_alter_qrcode_qr_as_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='qr_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_as_image',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_as_text',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensurance.file'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the QR Code', null=True),
        ),
    ]
