# Generated by Django 5.1.4 on 2025-01-21 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_qrcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of the order', null=True),
        ),
    ]
