# Generated by Django 5.1.4 on 2025-01-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_qrcode_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('Dynamic', 'Dynamic'), ('Static', 'Static'), ('Hybrid', 'Hybrid')], default='Dynamic', help_text='Type of the QR Code', max_length=7),
        ),
    ]
