# Generated by Django 5.1.4 on 2025-02-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_qrcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='data',
            field=models.JSONField(default=dict, help_text='Data associated with the QR Code'),
        ),
    ]
