# Generated by Django 5.1.4 on 2025-05-06 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensurance', '0010_file_data'),
        ('payment', '0011_qrcode_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaibPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of the payment', unique=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of the order')),
                ('pay_id', models.CharField(help_text='MAIB payment ID', max_length=36, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(help_text='Payment currency', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the payment', max_length=10)),
                ('client_name', models.CharField(blank=True, help_text='Client name', max_length=128, null=True)),
                ('client_email', models.EmailField(blank=True, help_text='Client email', max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, help_text='Client phone', max_length=40, null=True)),
                ('description', models.CharField(blank=True, help_text='Payment description', max_length=124, null=True)),
                ('payment_url', models.URLField(help_text='URL for payment processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict, help_text='Additional payment data')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensurance.file')),
            ],
            options={
                'verbose_name': 'MAIB Payment',
                'verbose_name_plural': 'MAIB Payments',
            },
        ),
    ]
