# Generated by Django 5.1.4 on 2025-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_maibpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maibpayment',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='maibpayment',
            name='currency',
            field=models.CharField(default='MDL', help_text='Payment currency', max_length=3),
        ),
        migrations.AlterField(
            model_name='maibpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the payment', max_length=10),
        ),
    ]
