# Generated by Django 5.1.4 on 2025-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_maibpayment_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maibpayment',
            name='uuid',
        ),
    ]
