# Generated by Django 5.1.4 on 2025-05-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_maibpayment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maibpayment',
            name='file',
        ),
    ]
