# Generated by Django 5.1.4 on 2025-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_remove_maibpayment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='maibpayment',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the payment has been used'),
        ),
    ]
